-- MySQL Script generated by MySQL Workbench
-- Sun Dec 13 21:21:50 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema safeassist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema safeassist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safeassist` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `safeassist` ;

-- -----------------------------------------------------
-- Table `safeassist`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`addresses` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip1` VARCHAR(5) NOT NULL,
  `zip2` VARCHAR(4) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` MEDIUMTEXT NULL,
  `password` VARCHAR(100) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `administrator` TINYINT(1) NULL DEFAULT 0,
  `remember_token` CHAR(100) NULL,
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`consumers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`consumers` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`consumers` (
  `id` INT NOT NULL,
  `sponsor` INT NOT NULL,
  `description` TEXT NULL,
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CONSUMER_USER1_idx` (`sponsor` ASC),
  INDEX `user_records` (`id` ASC, `sponsor` ASC),
  INDEX `fk_consumer_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_CONSUMER_USER1`
    FOREIGN KEY (`sponsor`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumer_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`agencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`agencies` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`agencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agency_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_agency_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`enterprises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`enterprises` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`enterprises` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT 'represents a group which acts as advocates and caretakers for consumers',
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enterprise_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_enterprise_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users_in_enterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users_in_enterprise` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users_in_enterprise` (
  `user` INT NOT NULL,
  `enterprise` INT NOT NULL,
  INDEX `fk_USERS_IN_ENTERPRISE_USER1_idx` (`user` ASC),
  INDEX `fk_USERS_IN_ENTERPRISE_ENTERPRISE1_idx` (`enterprise` ASC),
  CONSTRAINT `fk_USERS_IN_ENTERPRISE_USER1`
    FOREIGN KEY (`user`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_IN_ENTERPRISE_ENTERPRISE1`
    FOREIGN KEY (`enterprise`)
    REFERENCES `safeassist`.`enterprises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`roles` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`roles` (
  `id` INT NOT NULL,
  `role` ENUM('AGENT', 'NORMAL', 'ADMIN') NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users_has_enterprises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users_has_enterprises` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users_has_enterprises` (
  `users_id` INT NOT NULL,
  `enterprises_id` INT NOT NULL,
  `administers` TINYINT(1) NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`users_id`, `enterprises_id`),
  INDEX `fk_users_has_enterprises_enterprises1_idx` (`enterprises_id` ASC),
  INDEX `fk_users_has_enterprises_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_enterprises_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_enterprises_enterprises1`
    FOREIGN KEY (`enterprises_id`)
    REFERENCES `safeassist`.`enterprises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users_has_agencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users_has_agencies` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users_has_agencies` (
  `users_id` INT NOT NULL,
  `agencies_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`users_id`, `agencies_id`),
  INDEX `fk_users_has_agencies_agencies1_idx` (`agencies_id` ASC),
  INDEX `fk_users_has_agencies_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_agencies_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_agencies_agencies1`
    FOREIGN KEY (`agencies_id`)
    REFERENCES `safeassist`.`agencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
