-- MySQL Script generated by MySQL Workbench
-- Sun May 22 20:13:01 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema safeassist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema safeassist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safeassist` DEFAULT CHARACTER SET utf8 ;
USE `safeassist` ;

-- -----------------------------------------------------
-- Table `safeassist`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`addresses` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip1` VARCHAR(5) NOT NULL,
  `zip2` VARCHAR(4) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `disabled` TINYINT(1) NULL DEFAULT 0,
  `email` MEDIUMTEXT NULL,
  `password` VARCHAR(100) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `administrator` TINYINT(1) NULL DEFAULT 0,
  `remember_token` CHAR(100) NULL,
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`schools` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schools_addresses1_idx` (`address_id` ASC),
  CONSTRAINT `fk_schools_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`employers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`employers` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`employers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employers_addresses1_idx` (`address_id` ASC),
  CONSTRAINT `fk_employers_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`consumers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`consumers` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`consumers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `disabled` TINYINT(1) NULL DEFAULT 0,
  `sponsor` INT NOT NULL,
  `relationship` ENUM('self', 'parent', 'guardian', 'sibling', 'facility_agent', 'medical_worker', 'other') NOT NULL DEFAULT 'Other',
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `suffix` VARCHAR(45) NULL,
  `language` ENUM('english', 'spanish', 'other') NOT NULL DEFAULT 'English',
  `address_id` INT NOT NULL,
  `phone` VARCHAR(45) NULL,
  `gender` VARCHAR(1) NULL,
  `dob` DATETIME NOT NULL,
  `ssn` VARCHAR(45) NULL,
  `height` INT NOT NULL,
  `weight` INT NOT NULL,
  `eyes` ENUM('brown', 'hazel', 'blue', 'green', 'grey', 'amber') NOT NULL,
  `hair` ENUM('brown', 'black', 'blonde', 'red', 'grey', 'bald') NOT NULL,
  `marks` MEDIUMTEXT NULL,
  `physician` MEDIUMTEXT NULL,
  `contact_instructions` MEDIUMTEXT NULL,
  `bracelet` VARCHAR(100) NULL,
  `image` BLOB NULL,
  `employer_id` INT NULL,
  `employer_position` VARCHAR(45) NULL,
  `employer_contact` VARCHAR(45) NULL,
  `school_id` INT NULL,
  `school_contact` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CONSUMER_USER1_idx` (`sponsor` ASC),
  INDEX `user_records` (`id` ASC, `sponsor` ASC),
  INDEX `fk_consumer_address1_idx` (`address_id` ASC),
  INDEX `fk_consumers_schools1_idx` (`school_id` ASC),
  INDEX `fk_consumers_employers1_idx` (`employer_id` ASC),
  CONSTRAINT `fk_CONSUMER_USER1`
    FOREIGN KEY (`sponsor`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumer_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumers_schools1`
    FOREIGN KEY (`school_id`)
    REFERENCES `safeassist`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumers_employers1`
    FOREIGN KEY (`employer_id`)
    REFERENCES `safeassist`.`employers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`agencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`agencies` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`agencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agency_address1_idx` (`address_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_agency_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`enterprises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`enterprises` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`enterprises` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT 'represents a group which acts as advocates and caretakers for consumers',
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enterprise_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_enterprise_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users_in_enterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users_in_enterprise` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users_in_enterprise` (
  `user` INT NOT NULL,
  `enterprise` INT NOT NULL,
  INDEX `fk_USERS_IN_ENTERPRISE_USER1_idx` (`user` ASC),
  INDEX `fk_USERS_IN_ENTERPRISE_ENTERPRISE1_idx` (`enterprise` ASC),
  CONSTRAINT `fk_USERS_IN_ENTERPRISE_USER1`
    FOREIGN KEY (`user`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_IN_ENTERPRISE_ENTERPRISE1`
    FOREIGN KEY (`enterprise`)
    REFERENCES `safeassist`.`enterprises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`roles` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`roles` (
  `id` INT NOT NULL,
  `role` ENUM('AGENT', 'NORMAL', 'ADMIN') NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users_has_enterprises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users_has_enterprises` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users_has_enterprises` (
  `users_id` INT NOT NULL,
  `enterprises_id` INT NOT NULL,
  `administers` TINYINT(1) NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`users_id`, `enterprises_id`),
  INDEX `fk_users_has_enterprises_enterprises1_idx` (`enterprises_id` ASC),
  INDEX `fk_users_has_enterprises_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_enterprises_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_enterprises_enterprises1`
    FOREIGN KEY (`enterprises_id`)
    REFERENCES `safeassist`.`enterprises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`agency_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`agency_user` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`agency_user` (
  `agency_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`agency_id`, `user_id`),
  INDEX `fk_users_has_agencies_agencies1_idx` (`agency_id` ASC),
  INDEX `fk_users_has_agencies_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_agencies_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safeassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_agencies_agencies1`
    FOREIGN KEY (`agency_id`)
    REFERENCES `safeassist`.`agencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`contacts` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consumer_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contacts_addresses1_idx` (`address_id` ASC),
  INDEX `fk_contacts_consumers1_idx` (`consumer_id` ASC),
  CONSTRAINT `fk_contacts_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacts_consumers1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `safeassist`.`consumers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`medications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`medications` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`medications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`devices` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`impairments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`impairments` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`impairments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`consumer_medication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`consumer_medication` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`consumer_medication` (
  `consumer_id` INT NOT NULL,
  `medication_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_consumer_medication_consumers1_idx` (`consumer_id` ASC),
  INDEX `fk_consumer_medication_medications1_idx` (`medication_id` ASC),
  PRIMARY KEY (`consumer_id`, `medication_id`),
  CONSTRAINT `fk_consumer_medication_consumers1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `safeassist`.`consumers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumer_medication_medications1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `safeassist`.`medications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`consumer_device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`consumer_device` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`consumer_device` (
  `consumer_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_consumer_device_consumers1_idx` (`consumer_id` ASC),
  INDEX `fk_consumer_device_devices1_idx` (`device_id` ASC),
  PRIMARY KEY (`consumer_id`, `device_id`),
  CONSTRAINT `fk_consumer_device_consumers1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `safeassist`.`consumers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumer_device_devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `safeassist`.`devices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`consumer_impairment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`consumer_impairment` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`consumer_impairment` (
  `consumer_id` INT NOT NULL,
  `impairment_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`consumer_id`, `impairment_id`),
  INDEX `fk_consumer_impairment_impairments1_idx` (`impairment_id` ASC),
  CONSTRAINT `fk_consumer_impairment_consumers1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `safeassist`.`consumers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumer_impairment_impairments1`
    FOREIGN KEY (`impairment_id`)
    REFERENCES `safeassist`.`impairments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`conditions` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`conditions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`consumer_condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`consumer_condition` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`consumer_condition` (
  `consumer_id` INT NOT NULL,
  `condition_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`consumer_id`, `condition_id`),
  CONSTRAINT `fk_consumer_impairment_consumers10`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `safeassist`.`consumers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumer_impairment_impairments10`
    FOREIGN KEY ()
    REFERENCES `safeassist`.`conditions` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `safeassist`.`devices`
-- -----------------------------------------------------
START TRANSACTION;
USE `safeassist`;
INSERT INTO `safeassist`.`devices` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Walking Cane', NULL, NULL);
INSERT INTO `safeassist`.`devices` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Oxygen Tank', NULL, NULL);
INSERT INTO `safeassist`.`devices` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Wheelchair', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `safeassist`.`impairments`
-- -----------------------------------------------------
START TRANSACTION;
USE `safeassist`;
INSERT INTO `safeassist`.`impairments` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Blindness', NULL, NULL);
INSERT INTO `safeassist`.`impairments` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Deafness', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `safeassist`.`conditions`
-- -----------------------------------------------------
START TRANSACTION;
USE `safeassist`;
INSERT INTO `safeassist`.`conditions` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Autism', NULL, NULL);
INSERT INTO `safeassist`.`conditions` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Schizophrenia', NULL, NULL);
INSERT INTO `safeassist`.`conditions` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Bipolar Disorder', NULL, NULL);

COMMIT;

