-- MySQL Script generated by MySQL Workbench
-- Thu Aug 20 09:21:17 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema safeassist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema safeassist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safeassist` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `safeassist` ;

-- -----------------------------------------------------
-- Table `safeassist`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`address` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip1` VARCHAR(5) NOT NULL,
  `zip2` VARCHAR(4) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`user` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(85) NULL,
  `password` VARCHAR(85) NULL,
  `email` MEDIUMTEXT NULL,
  `usertype` ENUM('AGENT', 'NORMAL', 'ADMIN') NOT NULL,
  `remember_token` CHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`consumer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`consumer` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`consumer` (
  `id` INT NOT NULL,
  `sponsor` INT NOT NULL,
  `description` TEXT NULL,
  `last_update` TIMESTAMP NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CONSUMER_USER1_idx` (`sponsor` ASC),
  INDEX `user_records` (`id` ASC, `sponsor` ASC),
  INDEX `fk_consumer_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_CONSUMER_USER1`
    FOREIGN KEY (`sponsor`)
    REFERENCES `safeassist`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumer_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`agency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`agency` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`agency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agency_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_agency_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`agent` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`agent` (
  `user` INT NULL,
  `agency` INT NOT NULL,
  PRIMARY KEY (`user`),
  INDEX `fk_AGENT_ENTERPRISE1_idx` (`agency` ASC),
  CONSTRAINT `fk_AGENT_USER1`
    FOREIGN KEY (`user`)
    REFERENCES `safeassist`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENT_ENTERPRISE1`
    FOREIGN KEY (`agency`)
    REFERENCES `safeassist`.`agency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`enterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`enterprise` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`enterprise` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT 'represents a group which acts as advocates and caretakers for consumers',
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enterprise_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_enterprise_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `safeassist`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safeassist`.`users_in_enterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safeassist`.`users_in_enterprise` ;

CREATE TABLE IF NOT EXISTS `safeassist`.`users_in_enterprise` (
  `user` INT NOT NULL,
  `enterprise` INT NOT NULL,
  INDEX `fk_USERS_IN_ENTERPRISE_USER1_idx` (`user` ASC),
  INDEX `fk_USERS_IN_ENTERPRISE_ENTERPRISE1_idx` (`enterprise` ASC),
  CONSTRAINT `fk_USERS_IN_ENTERPRISE_USER1`
    FOREIGN KEY (`user`)
    REFERENCES `safeassist`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_IN_ENTERPRISE_ENTERPRISE1`
    FOREIGN KEY (`enterprise`)
    REFERENCES `safeassist`.`enterprise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
